-- ALTER TABLE big ADD COLUMN login VARCHAR(255) NOT NULL;
-- ALTER TABLE big ADD COLUMN hz VARCHAR(255) NOT NULL;
CREATE TABLE sign (
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
  );
